version: '3.8'

services:
  node:
    image: ghcr.io/millo-group/telemedicine_frontend:layout
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run start
    networks:
      inverseproxy_shared:

networks:
  inverseproxy_shared:
    external: true
